# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('uchileedxlogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdxLoginUserCourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(db_index=True, max_length=18, unique=True)),
                ('course', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('mode', models.TextField(choices=[(b'audit', b'audit'), (b'honor', b'honor')])),
                ('auto_enroll', models.BooleanField(default=True)),
            ],
        ),
    ]
