# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchileedxlogin', '0004_auto_20200414_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edxloginuser', options={
                'permissions': [
                    ('instructor_staff', 'instructor can enroll/unenroll users')]}, ), ]
