# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 20:07


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchileedxlogin', '0005_auto_20200420_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edxloginuser',
            options={
                'permissions': [
                    ('uchile_instructor_staff',
                     'instructor can enroll/unenroll users')]},
        ),
    ]
