# Generated by Django 2.2.13 on 2020-08-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchileedxlogin', '0006_auto_20200420_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edxloginusercourseregistration',
            name='mode',
            field=models.TextField(choices=[('audit', 'audit'), ('honor', 'honor')]),
        ),
    ]
