# Generated by Django 2.2.13 on 2020-09-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchileedxlogin', '0007_auto_20200828_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edxloginuser',
            name='run',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='edxloginusercourseregistration',
            name='run',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
