# Generated by Django 2.2.13 on 2020-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchileedxlogin', '0008_auto_20200930_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='edxloginuser',
            name='have_sso',
            field=models.BooleanField(default=True),
        ),
    ]
